/* MASAFY OS — data.js : projects + i18n dictionary */
'use strict';

const MASAFY = window.MASAFY = window.MASAFY || {};

/* ---------------- categories ---------------- */
MASAFY.CATS = [
  { id: 'saas', icon: '🌐', ja: 'SaaS / Web',  en: 'SaaS / Web' },
  { id: 'ai',   icon: '🤖', ja: 'AI / ML',     en: 'AI / ML' },
  { id: 'art',  icon: '🎨', ja: 'WebGLアート', en: 'WebGL Art' },
  { id: 'game', icon: '🎮', ja: 'ゲーム',      en: 'Games' },
  { id: 'ios',  icon: '📱', ja: 'iOS',         en: 'iOS' },
  { id: 'hw',   icon: '🔧', ja: 'ハードウェア', en: 'Hardware' },
  { id: 'sec',  icon: '🛡️', ja: 'セキュリティ', en: 'Security' },
];

/* ---------------- projects ----------------
   links: [type, url]  type: play|gh|doi|hf|store
   badge: LIVE | OSS | STORE | LAB | PRIVATE            */
MASAFY.PROJECTS = [
  /* SaaS / Web */
  { id: 'ichikazu', cat: 'saas', name: 'いちカズ / 1qaz.jp', badge: 'LIVE',
    ja: '短縮URLサービス。FastAPI＋systemd。Pro プラン（¥50/月）を Stripe で有料提供中。',
    en: 'URL shortener. FastAPI + systemd. Paid Pro plan (¥50/mo) live via Stripe.',
    links: [['play', 'https://1qaz.jp/'], ['gh', 'https://github.com/masafykun/ichikazu']] },
  { id: 'archivo', cat: 'saas', name: 'archivo.zip', badge: 'LIVE',
    ja: 'ファイル共有SaaS。Stripe による月額プランが実際に稼働している自前運用サービス。',
    en: 'File-sharing SaaS with a live Stripe subscription plan, self-hosted and self-operated.',
    links: [['play', 'https://archivo.1qaz.jp/']] },
  { id: 'dapi', cat: 'saas', name: 'd-api', badge: 'LIVE',
    ja: '日本語ダミーデータ生成API。氏名・住所などをAPIで配信。Pro/Biz の有料プランあり。',
    en: 'Japanese dummy-data API (names, addresses, …) with paid Pro/Biz tiers.',
    links: [['play', 'https://d.1qaz.jp/']] },
  { id: 'factura', cat: 'saas', name: 'Factura', badge: 'LIVE',
    ja: 'AIが請求書画像を構造化データへ変換するSaaS。',
    en: 'SaaS that converts invoice images into structured data with AI.',
    links: [['play', 'https://factura.1qaz.jp/']] },
  { id: 'vidconv', cat: 'saas', name: 'vidconv', badge: 'LIVE',
    ja: '動画変換SaaS。Node.js＋FFmpeg、10言語対応。',
    en: 'Video conversion SaaS. Node.js + FFmpeg, available in 10 languages.',
    links: [['play', 'https://vidconv.1qaz.jp/']] },
  { id: 'blockchat', cat: 'saas', name: 'block-chat', badge: 'OSS',
    ja: '自然言語で Scratch をコーディング。日本語の指示からブロックプログラムを生成する。',
    en: 'Code Scratch in natural language — generates block programs from plain Japanese.',
    links: [['gh', 'https://github.com/masafykun/block-chat-gui']] },
  { id: 'moon', cat: 'saas', name: 'MASAFY Moon City', badge: 'LIVE',
    ja: '月面都市に住むAI住人30人の暮らしが cron で毎日自動更新される観察サイト。',
    en: 'A lunar city of 30 AI residents whose lives auto-update daily via cron.',
    links: [['play', 'https://moon.1qaz.jp/'], ['gh', 'https://github.com/masafykun/moon-masafy']] },

  /* AI / ML */
  { id: 'ctf7b', cat: 'ai', name: 'masafee-ctf-7b', badge: 'OSS',
    ja: 'CTF writeup で QLoRA 学習した CTF 特化 7B モデル。GitHub / Hugging Face / Zenodo DOI / 論文の3チャンネルで公開。',
    en: 'A CTF-specialized 7B model (QLoRA on CTF writeups), published on GitHub / Hugging Face / Zenodo with DOI + paper.',
    links: [['gh', 'https://github.com/masafykun/masafee-ctf-7b'], ['hf', 'https://huggingface.co/masafy'], ['doi', 'https://doi.org/10.5281/zenodo.20413081']] },
  { id: 'lora', cat: 'ai', name: 'masafee-lora', badge: 'OSS',
    ja: '自宅GPUで学習したキャラクターLoRA。データセット設計から評価まで一人で完走、DOI付きで公開。',
    en: 'Character LoRA trained on a home GPU — dataset design to evaluation, published with a DOI.',
    links: [['gh', 'https://github.com/masafykun/masafee-lora'], ['doi', 'https://doi.org/10.5281/zenodo.20397946']] },
  { id: 'soseki', cat: 'ai', name: 'nanogpt-soseki', badge: 'OSS',
    ja: '青空文庫の夏目漱石84作品で、文字レベルGPTをゼロから学習。',
    en: 'A character-level GPT trained from scratch on 84 Natsume Sōseki works.',
    links: [['gh', 'https://github.com/masafykun/nanogpt-soseki']] },
  { id: 'embed', cat: 'ai', name: 'embedding-explore', badge: 'OSS',
    ja: 'text-embedding-3-large の3072次元を解剖する実験集。',
    en: 'Experiments dissecting the 3,072 dimensions of text-embedding-3-large.',
    links: [['gh', 'https://github.com/masafykun/embedding-explore']] },
  { id: 'fugu', cat: 'ai', name: 'Sakana Fugu Pipeline', badge: 'LIVE',
    ja: 'AIが毎朝ゲームを自動生成して公開するパイプライン。生成されたゲームはその場で遊べる。',
    en: 'A pipeline where AI auto-generates and publishes a game every morning — playable on the spot.',
    links: [['play', 'https://sakanagame.1qaz.jp/'], ['gh', 'https://github.com/masafykun/sakana-game']] },
  { id: 'fugucode', cat: 'ai', name: 'fugu-code', badge: 'OSS',
    ja: '自作のVS Codeエージェント拡張。寛容なコードブロックプロトコルでLLMにコーディングさせる。',
    en: 'A self-built VS Code agent extension that drives an LLM with a forgiving code-block protocol.',
    links: [['gh', 'https://github.com/masafykun/fugu-code']] },
  { id: 'npc', cat: 'ai', name: 'Minecraft AI NPC', badge: 'LAB',
    ja: 'LLM駆動のNPC3体がMinecraftサーバーに住んで自律行動する実験。',
    en: 'Three LLM-driven NPCs living and acting autonomously on a Minecraft server.',
    links: [] },

  /* WebGL Art */
  { id: 'voyage', cat: 'art', name: '航宙 — VOYAGE', badge: 'LIVE',
    ja: 'スクロール連動で宇宙を旅するシネマティック3D、全5章。Three.js＋GLSL。',
    en: 'A scroll-driven cinematic journey through space in five chapters. Three.js + GLSL.',
    links: [['play', 'https://voyage.1qaz.jp/'], ['gh', 'https://github.com/masafykun/voyage']] },
  { id: 'ink', cat: 'art', name: '墨流し — INK', badge: 'LIVE',
    ja: 'フル画面のGPU流体シミュレーション。WebGL2でNavier-Stokesを実装、外部ライブラリ0。',
    en: 'Full-screen GPU fluid simulation — Navier-Stokes in raw WebGL2, zero libraries.',
    links: [['play', 'https://ink.1qaz.jp/'], ['gh', 'https://github.com/masafykun/ink']] },
  { id: 'drive', cat: 'art', name: '走 — DRIVE', badge: 'LIVE',
    ja: 'ミニカーで低ポリの島を自由に走り回る。Three.js＋Rapier物理。',
    en: 'Drive a tiny car around a low-poly island. Three.js + Rapier physics.',
    links: [['play', 'https://drive.1qaz.jp/'], ['gh', 'https://github.com/masafykun/drive']] },
  { id: 'wake', cat: 'art', name: '航跡 — WAKE', badge: 'LIVE',
    ja: 'Gerstner波の海をスピードボートで駆ける、DRIVEの海版。',
    en: 'Race a speedboat across a Gerstner-wave ocean — DRIVE’s seafaring sibling.',
    links: [['play', 'https://wake.1qaz.jp/'], ['gh', 'https://github.com/masafykun/wake']] },
  { id: 'flux', cat: 'art', name: 'ゆらぎ — FLUX', badge: 'LIVE',
    ja: 'ジェネラティブ・パーティクルのアートサイト。Vite＋Canvas。',
    en: 'A generative particle art site. Vite + Canvas.',
    links: [['play', 'https://flux.1qaz.jp/'], ['gh', 'https://github.com/masafykun/yuragi-flux']] },
  { id: 'orb', cat: 'art', name: '鼓動 — ORB', badge: 'LIVE',
    ja: 'マウスに反応して脈動する3Dオーブ。Three.js＋GLSL。',
    en: 'A 3D orb that pulses in response to your cursor. Three.js + GLSL.',
    links: [['play', 'https://orb.1qaz.jp/'], ['gh', 'https://github.com/masafykun/kodou-orb']] },

  /* Games */
  { id: 'soccer', cat: 'game', name: 'Soccer Online', badge: 'LIVE',
    ja: '1対1のリアルタイム対戦WebGLサッカー。',
    en: 'Real-time 1v1 WebGL soccer.',
    links: [['play', 'https://soccer.1qaz.jp/']] },
  { id: 'oekaki', cat: 'game', name: 'お絵描き当てっこ', badge: 'LIVE',
    ja: 'リアルタイム対戦のお絵描きゲーム。Laravel＋Reverb（WebSocket）。',
    en: 'A real-time drawing-and-guessing battle. Laravel + Reverb (WebSocket).',
    links: [['play', 'https://oekaki.1qaz.jp/'], ['gh', 'https://github.com/masafykun/oekaki-battle']] },
  { id: 'aiquiz', cat: 'game', name: 'AI Quiz', badge: 'LIVE',
    ja: 'ローカルLLM（Ollama）が出題する4択クイズ＋全国ランキング。',
    en: 'Four-choice quizzes generated by a local LLM (Ollama), with a national ranking.',
    links: [['play', 'https://quiz.1qaz.jp/'], ['gh', 'https://github.com/masafykun/ai-quiz']] },

  /* iOS */
  { id: 'quietopia', cat: 'ios', name: 'Quietopia', badge: 'STORE',
    ja: 'スマホに触れない時間で惑星が育つウェルビーイングアプリ。App Storeで配信中。',
    en: 'A well-being app where a planet grows while you leave your phone alone. Live on the App Store.',
    links: [['store', 'https://apps.apple.com/jp/app/id6782968442']] },
  { id: 'watchpod', cat: 'ios', name: 'WatchPod', badge: 'LAB',
    ja: 'iPhoneなしで Apple Watch＋AirPods だけでMP3を聴くためのアプリ。提出準備中。',
    en: 'Listen to MP3s with just an Apple Watch + AirPods, no iPhone needed. Pre-submission.',
    links: [['gh', 'https://github.com/masafykun/WatchPod']] },
  { id: 'miru', cat: 'ios', name: '〜ミル兄弟シリーズ', badge: 'LAB',
    ja: 'テソミル（手相AI）／ナゾミル（水平思考パズル）／チエミル（クイズ）。開発中のiOS3兄弟。',
    en: 'TESOMIRU (palm-reading AI) / NAZOMIRU (lateral-thinking puzzles) / CHIEMIRU (quizzes) — three iOS apps in development.',
    links: [['gh', 'https://github.com/masafykun/TESOMIRU']] },

  /* Hardware */
  { id: 'ble', cat: 'hw', name: 'ble-lab', badge: 'LAB',
    ja: 'ESP32-S3 で BLE アドバタイズ挙動を検証する自宅ラボ。',
    en: 'A home lab probing BLE advertising behavior with an ESP32-S3.',
    links: [['gh', 'https://github.com/masafykun/ble-lab']] },
  { id: 'badusb', cat: 'hw', name: 'bad-usb', badge: 'LAB',
    ja: 'Adafruit Trinkey QT2040 を使った HID 注入の検証ラボ（自分のマシン限定）。',
    en: 'An HID-injection study lab on the Adafruit Trinkey QT2040 (own machines only).',
    links: [['gh', 'https://github.com/masafykun/bad-usb-trinkey-lab']] },
  { id: 'cat', cat: 'hw', name: '猫用トラッカー', badge: 'LAB',
    ja: 'XIAO nRF52840＋OpenHaystack で「探す」ネットワークに乗る猫トラッカーを3個試作。',
    en: 'Three prototype cat trackers riding the Find My network — XIAO nRF52840 + OpenHaystack.',
    links: [] },
  { id: 'wifilab', cat: 'hw', name: 'CTF Wi-Fi Lab', badge: 'LAB',
    ja: 'UTM上のKali＋ALFA AWUS036AC で組んだ無線CTF練習環境（自宅の自分のAP限定）。',
    en: 'A wireless CTF practice rig — Kali on UTM + ALFA AWUS036AC (own home APs only).',
    links: [] },

  /* Security */
  { id: 'opensoar', cat: 'sec', name: 'OpenSOAR', badge: 'OSS',
    ja: '自宅サーバーへの実攻撃（fail2ban/UFW/nginxログ）を世界地図に可視化するSOCダッシュボードのOSS版。',
    en: 'OSS edition of a SOC dashboard that maps real attacks on my servers (fail2ban/UFW/nginx logs) onto a world map.',
    links: [['gh', 'https://github.com/masafykun/opensoar']] },
  { id: 'osint', cat: 'sec', name: 'OSINT Dashboard', badge: 'PRIVATE',
    ja: 'Shodan風＋urlscan風を統合した自分用OSINTダッシュボード（非公開運用）。',
    en: 'A personal OSINT dashboard blending Shodan-style and urlscan-style views (private).',
    links: [] },
  { id: 'phishing', cat: 'sec', name: 'phishing-monitor', badge: 'PRIVATE',
    ja: '届いたフィッシングメールをIMAP経由でLLM判定・蓄積。累計9,700件超を自動監視（非公開運用）。',
    en: 'LLM-classifies phishing mail via IMAP — 9,700+ samples monitored automatically (private).',
    links: [] },
  { id: 'sshsafety', cat: 'sec', name: 'claude-ssh-mcp-safety', badge: 'OSS',
    ja: 'AIにサーバー管理を任せるための危険コマンドガード。rm等の誤操作をフックで防ぐ。',
    en: 'A dangerous-command guard for letting AI manage servers — hooks that block destructive ops.',
    links: [['gh', 'https://github.com/masafykun/claude-ssh-mcp-safety']] },
  { id: 'rclonekit', cat: 'sec', name: 'RcloneCryptKit', badge: 'OSS',
    ja: 'rclone crypt の復号をゼロから再実装。実バックアップ全件で検証PASS。',
    en: 'rclone crypt decryption re-implemented from scratch — verified against real backups.',
    links: [['gh', 'https://github.com/masafykun/RcloneCryptKit']] },
];

/* ---------------- link labels ---------------- */
MASAFY.LINK_LABELS = {
  play:  { ja: '▶ あそぶ',    en: '▶ Play' },
  gh:    { ja: '↗ GitHub',    en: '↗ GitHub' },
  doi:   { ja: '📄 DOI',      en: '📄 DOI' },
  hf:    { ja: '🤗 HF',       en: '🤗 HF' },
  store: { ja: ' App Store', en: ' App Store' },
};

/* ---------------- i18n ---------------- */
MASAFY.I18N = {
  ja: {
    'menubar.os': 'MASAFY OS',
    'boot.skip': 'クリックでスキップ ▸',
    'dock.terminal': 'ターミナル',
    'dock.works': 'つくったもの',
    'dock.about': '自己紹介',
    'dock.security': 'セキュリティ',
    'dock.mail': '連絡先',
    'dock.console': 'コンソール',
    'dock.root': 'ROOT',
    'win.terminal': 'ターミナル — masafy@os',
    'win.works': 'つくったもの — /works',
    'win.about': '自己紹介 — README.md',
    'win.security': 'セキュリティ — /sec',
    'win.mail': '連絡先 — mail',
    'win.console': 'コンソール — /var/log/os.log',
    'win.root': 'ROOT — 隠し領域',
    'icon.readme': 'readme.txt',
    'icon.works': 'works',
    'icon.flag': 'flag.txt',
    'widget.live': 'LIVE',
    'widget.github': 'GitHub',
    'widget.qiita': 'Qiita 最新記事',
    'widget.repos': '公開リポジトリ',
    'widget.followers': 'フォロワー',
    'widget.offline': 'オフライン（後で再試行）',
    'works.all': 'すべて',
    'works.hint': '← カテゴリを選ぶか、カードをクリック。ターミナルの `open <id>` でも開けます。',
    'works.links': 'リンク',
    'about.name': 'Masato Suzuki / MASAFY',
    'about.role': 'セキュリティエンジニア（大手通信キャリア勤務）',
    'about.lead': '「守る・自動化する・つくる」。昼はSOCでセキュリティ対応を自動化し、夜と週末は20以上のサービスを自分のサーバーで動かし続けている、手を動かすタイプのエンジニアです。',
    'about.p1.h': '🛡️ 守る — Security',
    'about.p1.b': '本業はセキュリティ対応の自動化。発明者として特許2件を出願（1件は勤務先から、1件は個人で電子出願）。CTF特化の7Bモデルを自作してDOI付きで公開するなど、「守る技術」を研究として残すことも大事にしています。',
    'about.p2.h': '🤖 自動化する — AI',
    'about.p2.b': 'LoRA・QLoRAの学習からローカルLLM運用、AIが毎朝ゲームを自動生成するパイプラインまで、AIは「使う」だけでなく「仕組みごと作る」派。自宅GPUサーバーが今日も回っています。',
    'about.p3.h': '🔧 つくる — Maker',
    'about.p3.b': 'SaaS・WebGLアート・iOSアプリ・電子工作まで、思いついたら作って公開。Stripe課金が実際に動いているサービスも複数あります。このOS自体も外部ライブラリなしのフルスクラッチです。',
    'about.hl.h': 'HIGHLIGHTS',
    'about.hl.1': '📄 特許2件を発明者として出願（セキュリティ自動化／地域社会×分散AI）',
    'about.hl.2': '📱 iOSアプリ「Quietopia」をApp Storeで配信中',
    'about.hl.3': '🤖 CTF特化7Bモデルを学習し、論文＋DOI付きで公開',
    'about.hl.4': '📺 AbemaTV「学生イノベーションバトル」出演／🌏 海外ボランティア参加',
    'about.edu.h': 'EDUCATION',
    'about.edu.b': 'プログラミングを教えてきた子どもは延べ60人以上、コンテスト等の入賞8名。CoderDojo溝口での活動など、「難しい」を「楽しい」に変える教育がライフワークです。',
    'about.link.h': 'MORE',
    'about.link.b': '正式なポートフォリオは masafy.org、工房ツアー版は me.1qaz.jp にあります。ここは3つめの「操作するポートフォリオ」。',
    'sec.lead': 'セキュリティエンジニアとしての顔。守りは本業、攻めはラボの中だけ。',
    'sec.patents.h': '📄 特許（発明者）',
    'sec.pat1': '特開2025-056374 — セキュリティ対応の自動化。不審ファイル検知時にMLモデルが自動でヒアリングを行う仕組み。',
    'sec.pat2': '特願2026-121582 — 分散AI推論による地域社会行動支援およびリスク予兆検知システム。弁理士なしの個人電子出願。',
    'sec.pat1.link': '↗ Google Patents で読む',
    'sec.pat2.link': '↗ 詳細ページ（masafy.org）',
    'sec.works.h': '🛡️ セキュリティの制作物',
    'sec.ctf.h': '🚩 CTF',
    'sec.ctf.b': 'このOSにはフラグが1つ隠されています。ターミナルを開いて `nmap` から始めてみてください。見つけた人だけが開ける画面があります。',
    'mail.lead': 'お仕事・コラボ・質問、なんでもどうぞ。',
    'mail.email': 'メール',
    'mail.links': 'リンク',
    'console.lead': 'このOSのイベントログ（可観測性もデザインのうち）',
    'root.h': 'root@masafy-os — アクセス許可',
    'root.b1': 'フラグ発見おめでとうございます！🎉 あなたのように「とりあえず触って、調べて、掘る」人と仕事をするのが好きです。',
    'root.b2': 'このOSは外部ライブラリゼロ・フルスクラッチの vanilla JS で書かれています。ウィンドウマネージャも、このCTFも、ぜんぶ手書きです。ソースは GitHub（masafykun/masafy-os）で公開しています。',
    'root.b3': 'せっかくなので、隠しコマンド `neofetch --masafy` もどうぞ。',
    'toast.rootUnlocked': '🔓 ROOT がDockに追加されました',
  },
  en: {
    'menubar.os': 'MASAFY OS',
    'boot.skip': 'click to skip ▸',
    'dock.terminal': 'Terminal',
    'dock.works': 'Works',
    'dock.about': 'About',
    'dock.security': 'Security',
    'dock.mail': 'Contact',
    'dock.console': 'Console',
    'dock.root': 'ROOT',
    'win.terminal': 'Terminal — masafy@os',
    'win.works': 'Works — /works',
    'win.about': 'About — README.md',
    'win.security': 'Security — /sec',
    'win.mail': 'Contact — mail',
    'win.console': 'Console — /var/log/os.log',
    'win.root': 'ROOT — hidden area',
    'icon.readme': 'readme.txt',
    'icon.works': 'works',
    'icon.flag': 'flag.txt',
    'widget.live': 'LIVE',
    'widget.github': 'GitHub',
    'widget.qiita': 'Latest on Qiita',
    'widget.repos': 'public repos',
    'widget.followers': 'followers',
    'widget.offline': 'offline (retry later)',
    'works.all': 'All',
    'works.hint': '← Pick a category or click a card. You can also `open <id>` from the Terminal.',
    'works.links': 'Links',
    'about.name': 'Masato Suzuki / MASAFY',
    'about.role': 'Security Engineer (major telecom carrier)',
    'about.lead': 'Protect, automate, build. By day I automate security operations in a SOC; by night I keep 20+ services running on my own servers. I’m the hands-on type.',
    'about.p1.h': '🛡️ Protect — Security',
    'about.p1.b': 'My day job is automating security response. I’ve filed two patents as an inventor (one through my employer, one filed personally). I also publish defensive research — like a self-trained CTF-specialized 7B model with a DOI.',
    'about.p2.h': '🤖 Automate — AI',
    'about.p2.b': 'From LoRA/QLoRA training and local LLM ops to a pipeline where AI auto-generates a game every morning — I don’t just use AI, I build the machinery around it. My home GPU server is running right now.',
    'about.p3.h': '🔧 Build — Maker',
    'about.p3.b': 'SaaS, WebGL art, iOS apps, electronics — if I can imagine it, I ship it. Several services have real paying users via Stripe. This OS itself is written from scratch with zero external libraries.',
    'about.hl.h': 'HIGHLIGHTS',
    'about.hl.1': '📄 Two patents filed as inventor (security automation / community × distributed AI)',
    'about.hl.2': '📱 iOS app “Quietopia” live on the App Store',
    'about.hl.3': '🤖 Trained a CTF-specialized 7B model, published with paper + DOI',
    'about.hl.4': '📺 Appeared on AbemaTV’s student innovation battle / 🌏 overseas volunteering',
    'about.edu.h': 'EDUCATION',
    'about.edu.b': 'I’ve taught programming to 60+ kids, eight of whom won contests. Turning “hard” into “fun” — including activity at CoderDojo Mizonokuchi — is my life work.',
    'about.link.h': 'MORE',
    'about.link.b': 'The formal portfolio lives at masafy.org, and the atelier-tour version at me.1qaz.jp. This is the third one: a portfolio you operate.',
    'sec.lead': 'The security side of me. Defense is my day job; offense stays inside the lab.',
    'sec.patents.h': '📄 Patents (as inventor)',
    'sec.pat1': 'JP 2025-056374 — automating security response: an ML model interviews users automatically when a suspicious file is detected.',
    'sec.pat2': 'JP App. 2026-121582 — community behavior support & risk-sign detection via distributed AI inference. Filed personally, no attorney.',
    'sec.pat1.link': '↗ Read on Google Patents',
    'sec.pat2.link': '↗ Details (masafy.org)',
    'sec.works.h': '🛡️ Security works',
    'sec.ctf.h': '🚩 CTF',
    'sec.ctf.b': 'One flag is hidden in this OS. Open the Terminal and start with `nmap`. Those who find it unlock a hidden screen.',
    'mail.lead': 'Work, collaboration, questions — all welcome.',
    'mail.email': 'Email',
    'mail.links': 'Links',
    'console.lead': 'Event log of this OS (observability is part of the design)',
    'root.h': 'root@masafy-os — access granted',
    'root.b1': 'Congrats on capturing the flag! 🎉 I love working with people who poke, inspect, and dig.',
    'root.b2': 'This OS is hand-written vanilla JS with zero external libraries — the window manager and this CTF included. Source is public at GitHub (masafykun/masafy-os).',
    'root.b3': 'One more secret for you: try `neofetch --masafy`.',
    'toast.rootUnlocked': '🔓 ROOT added to the Dock',
  },
};

/* ---------------- contact links ---------------- */
MASAFY.CONTACTS = [
  ['✉️', 'Email', 'mailto:masafy.masato@gmail.com', 'masafy.masato@gmail.com'],
  ['🐙', 'GitHub', 'https://github.com/masafykun', 'github.com/masafykun'],
  ['🕊️', 'X', 'https://x.com/masafyorg', '@masafyorg'],
  ['📝', 'Qiita', 'https://qiita.com/masafy', 'qiita.com/masafy'],
  ['🤗', 'Hugging Face', 'https://huggingface.co/masafy', 'huggingface.co/masafy'],
  ['💼', 'LinkedIn', 'https://www.linkedin.com/in/masato-suzuki-b801ab360', 'in/masato-suzuki-b801ab360'],
  ['🎓', 'ORCID', 'https://orcid.org/0009-0000-7977-2756', '0009-0000-7977-2756'],
  ['🏠', 'masafy.org', 'https://masafy.org/', 'masafy.org'],
];

/* ---------------- CTF ---------------- */
MASAFY.CTF = {
  flag: 'FLAG{m4s4fy_s3cur3_by_des1gn}',
  b64: 'RkxBR3ttNHM0ZnlfczNjdXIzX2J5X2RlczFnbn0=',
};
